return {
  diagnostics = {
    Error = '',
    Warn = '󱟪',
    Info = '󰽁',
    Hint = '',
  },
  git = {
    Branch = '',
    Modify = '',
    Add = '',
    Delete = '',
    Untracked = '',
    Ignored = '',
    Unstaged = '󱋭',
    Staged = '',
    Conflict = '',
  },
  file = {
    ModifiedFile = '',
    ReadOnlyFile = '',
    UnNamedFile = '󱀶',
    NewFile = '',
  },
  cmp_kinds = {
    Text = '  ',
    Method = '  ',
    Function = '  ',
    Constructor = '  ',
    Field = '  ',
    Variable = '  ',
    Class = '  ',
    Interface = '  ',
    Module = '  ',
    Property = '  ',
    Unit = '  ',
    Value = '  ',
    Enum = '  ',
    Keyword = '  ',
    Snippet = '  ',
    Color = '  ',
    File = '  ',
    Reference = '  ',
    Folder = '  ',
    EnumMember = '  ',
    Constant = '  ',
    Struct = '  ',
    Event = '  ',
    Operator = '  ',
    TypeParameter = '  ',
    CmpItemKindCopilot = '  ',
  },
  copilot = {
    Normal = '',
    Error = '',
    Warning = '',
  },
}
