require 'custom.config.ibl'
require 'custom.config.opts'
require 'custom.config.utils'
require 'custom.config.keybindings'
require 'custom.config.diagnostics'
require 'custom.config.autocommands'
require 'custom.config.tusan_lualine'
